### ISSUE TITLE
When the sun and moon are aligned on the 5th forte night the UUID is less random

### ISSUE THREAD

**Issue by interlock** [monicao/angular-uuid4#10]

**Comment by monicao** [comment]
![https://s-media-cache-ak0.pinimg.com/736x/ac/8d/75/ac8d75fd12398de589724b4dabc8fdc5.jpg](https://s-media-cache-ak0.pinimg.com/736x/ac/8d/75/ac8d75fd12398de589724b4dabc8fdc5.jpg)
