### ISSUE TITLE
License of angular-uuid4 is incorrectly written in npm.

### ISSUE THREAD

**Issue by soimsoim** [monicao/angular-uuid4#11]
When I check the LICENSE.txt in this repository, angular-uuid4 is released under Apache-2.0. 
However, in npm(https://www.npmjs.com/package/angular-uuid4), license information is written as MIT.

**Comment by monicao** [comment]
Thank you for flagging this! I will update the licensing information soon.

**Comment by monicao** [comment]
The information was updated as of Sep 10, 2019.
