### ISSUE TITLE
Generated UUIDs fail validation

### ISSUE THREAD

**Issue by TomSeldon** [monicao/angular-uuid4#7]
## Problem
Creating a UUID with `uuid4.generate` and validating that UUID with `uuid4.validate` sometimes fails.

## Example code
Running in Karma/Jasmine:

```javascript
var uuid = uuid4.generate();

expect(uuid4.validate(uuid)).toBe(true); // pot luck whether this passes
```

Sometimes passes, sometimes fails. No code or environment changes: The only difference is the generated UUID.

## Replication
I've only been able to replicate this when running on PhantomJS running with Karma and Jasmine. I've tried replicating this in a *real* browser and was unable to replicate the issue (all generated UUIDs were valid).

I'm unsure of the limitations of PhantomJS and its implications on this library, or even if this is genuinely a compatibility issue with PhantomJS or something else entirely (though it seems like it is).

**Comment by monicao** [comment]
I tried to replicate this. Ran the tests 10 times, but did not get any failures. What version of phantomjs are you running? I have `1.9.8`.
